resume:
pretrain:
seed: 1024
data:
    dataset: kinetics400
    modality: RGB
    num_segments: 8
    seg_length: 1
    split: 1
    batch_size: 64
    workers: 16
    gpus: 4
    num_classes: 400
    image_tmpl: 'img_{:05d}.jpg'
    flow_tmpl: '{}_{:05d}.jpg'
    train_list: 'lists/k4001/train_frames_new.txt' # /mnt/lustre/share/mapingchuan/dataset/kinetics400/split1/trainlist.txt
    val_list: 'lists/k4001/val_frames_re.txt' #
    label_list: 'lists/kinetics_400_labels.csv'
    index_bias: 1
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
network:
    arch: ViT-B/32  #ViT-B/32 ViT-B/16
    init: True
    tsm: False
    drop_out: 0.0 # probability of an element to be zeroed
    emb_dropout: 0.0 # probability of embedding to be zeroed
    version: ''
    bn_momentum: 0.1
    consensus_type: avg
    type: clip_k400
    sim_header: "Transf"  #Transf   meanP  LSTM Conv_1D Transf_cls
    joint: False
    describe:
solver:
    type: cosine
    epochs: 50
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6
    lr_warmup_step: 5
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: False
    ratio: 1
    f_ratio: 10
logging:
    print_freq: 10
    eval_freq: 1