name: base
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - appdirs=1.4.4=pyh9f0ad1d_0
  - audioread=2.1.9=py38h578d9bd_0
  - av=8.0.3=py38h2c5b837_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h516909a_3
  - ca-certificates=2021.5.30=ha878542_0
  - certifi=2021.5.30=py38h578d9bd_0
  - cffi=1.14.3=py38h261ae71_2
  - chardet=3.0.4=py38h06a4308_1003
  - conda=4.10.3=py38h578d9bd_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - cryptography=3.2.1=py38h3c74f83_1
  - cycler=0.10.0=py_2
  - ffmpeg=4.3.1=h3215721_1
  - freetype=2.10.4=h7ca028e_0
  - gettext=0.19.8.1=h5e8e0c9_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=2.10=py_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py38h82cb98a_0
  - lame=3.100=h14c3975_1001
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=he1b5a44_0
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=h14aa051_18
  - libgfortran4=7.5.0=h14aa051_18
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libogg=1.3.2=h516909a_1002
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - librosa=0.8.0=pyh9f0ad1d_0
  - libsndfile=1.0.29=he1b5a44_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=hc3755c2_3
  - libvorbis=1.3.7=he1b5a44_0
  - llvmlite=0.34.0=py38h4f45e52_2
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib-base=3.3.3=py38h5c7f4ab_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - numba=0.51.2=py38hc5bc63f_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h7f98852_0
  - packaging=20.9=pyh44b312d_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38h06a4308_0
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.8.5=h7579374_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - resampy=0.2.2=py_0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - scikit-learn=0.23.2=py38h5d63f67_3
  - setuptools=50.3.1=py38h06a4308_1
  - six=1.15.0=py38h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h25fe258_0
  - tqdm=4.51.0=pyhd3eb1b0_0
  - urllib3=1.25.11=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - x264=1!152.20180806=h14c3975_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - absl-py==0.13.0
    - addict==2.4.0
    - aiohttp==3.7.4.post0
    - antlr4-python3-runtime==4.8
    - apex==0.1
    - async-timeout==3.0.1
    - attrs==21.2.0
    - black==21.4b2
    - cachetools==4.2.2
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - configparser==5.0.2
    - contiguous-params==1.0.0
    - cython==0.29.23
    - dataclasses==0.6
    - decorator==4.4.2
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - dotmap==1.3.23
    - einops==0.3.0
    - fairseq==0.10.2
    - fire==0.4.0
    - fsspec==2021.6.1
    - ftfy==6.0.3
    - future==0.18.2
    - fvcore==0.1.5
    - gitdb==4.0.7
    - gitpython==3.1.18
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.1
    - hydra-core==1.1.0
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - importlib-resources==5.2.0
    - iopath==0.1.8
    - jpeg4py==0.1.4
    - lightseq==2.0.3
    - lmdb==1.2.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - mmcv-full==1.3.9
    - model-index==0.1.11
    - moviepy==1.0.3
    - msgpack-python==0.5.6
    - multidict==5.1.0
    - multiprocess==0.70.12.2
    - mypy-extensions==0.4.3
    - ninja==1.10.0.post2
    - numpy==1.20.3
    - nvidia-dali-cuda110==1.3.0
    - nvidia-pyindex==1.0.9
    - oauthlib==3.1.1
    - omegaconf==2.1.0
    - opencv-contrib-python==4.1.2.30
    - opencv-python==4.1.2.30
    - openmim==0.1.2
    - ordered-set==4.0.2
    - pandas==1.2.3
    - parameterized==0.8.1
    - pathos==0.2.8
    - pathspec==0.9.0
    - pathtools==0.1.2
    - pillow==8.2.0
    - pip==21.0.1
    - portalocker==2.0.0
    - pox==0.3.0
    - ppft==1.6.6.4
    - prefetch-generator==1.0.1
    - proglog==0.1.9
    - promise==2.3
    - protobuf==3.15.6
    - psutil==5.8.0
    - pyarrow==4.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.2
    - pydeprecate==0.3.0
    - pydot==1.4.2
    - pytorch-lightning==1.3.8
    - pytorchvideo==0.1.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - randaugment==0.1
    - regex==2021.7.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacrebleu==1.5.1
    - scipy==1.6.1
    - sentry-sdk==1.3.1
    - shortuuid==1.0.1
    - simplejson==3.17.3
    - sklearn==0.0
    - smmap==4.0.0
    - subprocess32==3.5.4
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.1
    - termcolor==1.1.0
    - toml==0.10.2
    - torch==1.8.1+cu111
    - torchaudio==0.8.1
    - torchmetrics==0.4.1
    - torchvision==0.9.1+cu111
    - typing-extensions==3.7.4.3
    - umsgpack==0.1.0
    - wandb==0.12.0
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - yacs==0.1.8
    - yapf==0.31.0
    - yarl==1.6.3
    - zipp==3.4.1
prefix: /home/ock/miniconda3
